as yet unclassified
buildOn: aBuilder

	aBuilder
		addHeader: 'Elements';
		addSectionHeader: 'Primitives';
		addBlock: 'Button' as: LPButton new;
		addBlock: 'Row' as: LPRow new;
		addBlock: 'Column' as: LPColumn new;
		addSectionHeader: 'New Side Effect';
		addBlock: 'LPSideEffect' as: LPSideEffect new;
		addSectionHeader: 'New Behavior';
		addSectionHeader: 'New Component';
		addBlock: 'LPComponent' as: LPComponent new